<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $productRecords = [
            [
                'category_id' => 1,
                'brand_id' => 1,
                'product_name' => 'Product A',
                'product_url' => 'product-a',
                'quantity' => 100,
                'product_code' => 'P001',
                'product_color' => 'Red',
                'family_colors' => 'Red, Blue, Green',
                'group_code' => 'G001',
                'product_price' => 99.99,
                'product_discount' => 10.00,
                'discount_type' => 'Fixed',
                'final_price' => 89.99,
                'product_weight' => 1.2,
                'product_video' => 'product_a.mp4',
                'description' => 'Description for Product A',
                'wash_care' => 'Hand wash only',
                'keywords' => 'red, product, A',
                'pattern' => 'Solid',
                'meta_title' => 'Product A - Red',
                'meta_description' => 'Buy Product A in red color at a discount',
                'meta_keyword' => 'Product A, red, discount',
                'is_featured' => 'Yes',
                'status' => 1,
            ],
            [
                'category_id' => 2,
                'brand_id' => 2,
                'product_name' => 'Product B',
                'product_url' => 'product-b',
                'quantity' => 100,
                'product_code' => 'P002',
                'product_color' => 'Blue',
                'family_colors' => 'Blue, Black, White',
                'group_code' => 'G002',
                'product_price' => 149.99,
                'product_discount' => 20.00,
                'discount_type' => 'Percentage',
                'final_price' => 119.99,
                'product_weight' => 1.5,
                'product_video' => 'product_b.mp4',
                'description' => 'Description for Product B',
                'wash_care' => 'Machine wash',
                'keywords' => 'blue, product, B',
                'pattern' => 'Striped',
                'meta_title' => 'Product B - Blue',
                'meta_description' => 'Buy Product B in blue color with a percentage discount',
                'meta_keyword' => 'Product B, blue, percentage discount',
                'is_featured' => 'No',
                'status' => 1,
            ],
            [
                'category_id' => 3,
                'brand_id' => 1,
                'product_name' => 'Product C',
                'product_url' => 'product-c',
                'quantity' => 100,
                'product_code' => 'P003',
                'product_color' => 'Green',
                'family_colors' => 'Green, Yellow',
                'group_code' => 'G003',
                'product_price' => 79.99,
                'product_discount' => 5.00,
                'discount_type' => 'Fixed',
                'final_price' => 74.99,
                'product_weight' => 1.0,
                'product_video' => 'product_c.mp4',
                'description' => 'Description for Product C',
                'wash_care' => 'Dry clean only',
                'keywords' => 'green, product, C',
                'pattern' => 'Printed',
                'meta_title' => 'Product C - Green',
                'meta_description' => 'Get Product C in green color with a fixed discount',
                'meta_keyword' => 'Product C, green, fixed discount',
                'is_featured' => 'Yes',
                'status' => 0,
            ],
            [
                'category_id' => 4,
                'brand_id' => 2,
                'product_name' => 'Product D',
                'product_url' => 'product-d',
                'quantity' => 100,
                'product_code' => 'P004',
                'product_color' => 'Yellow',
                'family_colors' => 'Yellow, Orange',
                'group_code' => 'G004',
                'product_price' => 119.99,
                'product_discount' => 15.00,
                'discount_type' => 'Fixed',
                'final_price' => 104.99,
                'product_weight' => 1.3,
                'product_video' => 'product_d.mp4',
                'description' => 'Description for Product D',
                'wash_care' => 'Hand wash only',
                'keywords' => 'yellow, product, D',
                'pattern' => 'Plaid',
                'meta_title' => 'Product D - Yellow',
                'meta_description' => 'Buy Product D in yellow color with a fixed discount',
                'meta_keyword' => 'Product D, yellow, discount',
                'is_featured' => 'No',
                'status' => 1,
            ],
            [
                'category_id' => 5,
                'brand_id' => 3,
                'product_name' => 'Product E',
                'product_url' => 'product-e',
                'quantity' => 100,
                'product_code' => 'P005',
                'product_color' => 'Black',
                'family_colors' => 'Black, Grey',
                'group_code' => 'G005',
                'product_price' => 199.99,
                'product_discount' => 25.00,
                'discount_type' => 'Percentage',
                'final_price' => 149.99,
                'product_weight' => 1.4,
                'product_video' => 'product_e.mp4',
                'description' => 'Description for Product E',
                'wash_care' => 'Machine wash',
                'keywords' => 'black, product, E',
                'pattern' => 'Solid',
                'meta_title' => 'Product E - Black',
                'meta_description' => 'Get Product E in black color at a discount',
                'meta_keyword' => 'Product E, black, discount',
                'is_featured' => 'Yes',
                'status' => 1,
            ],
    ];

    Product::insert($productRecords);

    }
}
